language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm run-script lint
after_success: npm run coverage